name: Mealting Pot project developer blog
description: Blogging about the evolution of the Mealting Pot project
meta_description: "Mealting Pot Developer blog"

aboutPage: true

markdown: redcarpet
highlighter: pygments
github: [Repository metadata]

paginate: 20
baseurl: /dev-blog
domain_name: 'https://mealting-pot.github.io/dev-blog'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://mealting-pot.github.io/dev-blog'
author:         'Mealting Pot'
authorTwitter:  ''

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
